# Generated by Django 3.2.4 on 2021-08-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SenderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('created', models.CharField(max_length=50)),
                ('t_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=200)),
            ],
        ),
    ]
