# Generated by Django 3.2.4 on 2021-08-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
