# Generated by Django 3.2.4 on 2021-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210810_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('val', models.CharField(max_length=20)),
                ('broadcast_name', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=20)),
            ],
        ),
    ]
