# Generated by Django 3.2.4 on 2021-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('val', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=20)),
            ],
        ),
    ]
