# Generated by Django 3.2.4 on 2021-08-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apidata_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SenderData',
        ),
    ]
