# Generated by Django 3.2.4 on 2021-08-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_createcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SenderData',
        ),
    ]
