# Generated by Django 3.2.4 on 2021-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_senderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('eventType', models.CharField(max_length=255)),
                ('statusString', models.CharField(max_length=255)),
                ('waId', models.CharField(max_length=255)),
            ],
        ),
    ]
