# Generated by Django 3.2.4 on 2021-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_senderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('created', models.CharField(max_length=50)),
                ('t_id', models.TextField()),
            ],
        ),
    ]
